version: "3"
services:
  widoki_manager:
    image: widoki_manager
    ports:
      - "8090:8080"
    networks:
      - widoki-api-port-manager
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    depends_on:
      - mysql

  mysql:
    container_name: "mysql"
    image: mysql
    networks:
      - widoki-api-port-manager
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_DATABASE=widokidb?createDatabaseIfNotExist=true
    ports:
      - "3306:3306"
    volumes:
      - /opt/mysql_data:/var/lib/mysql

networks:
  widoki-api-port-manager: