spring:
  flyway:
    baseline-on-migrate: true
    schema: 'widokidb'
  datasource:
    url: 'jdbc:mysql://localhost:3306/widokidb?createDatabaseIfNotExist=true'
    username: 'root'
    password: 'root'

logging:
  level:
    org:
      hibernate:
        SQL=debug: