spring:
  jpa:
  flyway:
    enabled: true
  datasource:
    url: 'jdbc:mysql://mysql:3306/widokidb'
    username: 'root'
    password: 'root'

logging:
  level:
    org:
      hibernate:
        SQL=debug: